# -*- coding: utf-8 -*-
"""202401100700094_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4AvD_30cMEbf9idwKHihzkKAC97rgBq
"""

import random
import time
import threading

LOWER_TEMP_THRESHOLD = 10
UPPER_TEMP_THRESHOLD = 45
def monitor_temperature(stop_event):
    print(f"Classification: Hot (Above {UPPER_TEMP_THRESHOLD}°C), Cold (Below {LOWER_TEMP_THRESHOLD}°C)\n")

    while not stop_event.is_set():
        current_temp = random.uniform(-5, 60)
        print(f"Current Temperature: {current_temp:.2f}°C")
        if current_temp > UPPER_TEMP_THRESHOLD:
            print(f"ALERT: Temperature is HIGH ({current_temp:.2f}°C)\n")
        elif current_temp < LOWER_TEMP_THRESHOLD:
            print(f"ALERT: Temperature is LOW ({current_temp:.2f}°C)\n")
        else:
            print("Temperature is normal\n")
        time.sleep(2)

def stop_monitoring(stop_event):
    input("Press Enter to stop monitoring...\n")
    stop_event.set()
    print("Monitoring stopped. Exiting program...")

if _name_ == "_main_":
    stop_event = threading.Event()
    monitor_thread = threading.Thread(target=monitor_temperature, args=(stop_event,))
    monitor_thread.start()
    stop_thread = threading.Thread(target=stop_monitoring, args=(stop_event,))
    stop_thread.start()
    monitor_thread.join()
    stop_thread.join()